"""
kaal_config.py
All configuration. No hardcoded watchlist here.
Watchlist is dynamically generated by evening scan → saved to data/watchlist.txt
"""
import os

def load_env():
    for path in [
        os.path.expanduser("~/kaal/kaal_v2/kaal/.env"),
        os.path.expanduser("~/kaal/.env"),
        os.path.join(os.path.dirname(__file__), ".env"),
    ]:
        if os.path.exists(path):
            for line in open(path):
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())
            break

load_env()

# ── TELEGRAM ──────────────────────────────────────────────
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT  = os.environ.get("TELEGRAM_CHAT_ID", "")

# ── GROQ + GEMINI ─────────────────────────────────────────
GROQ_API_KEY   = os.environ.get("GROQ_API_KEY", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

# ── EXTRA LLM KEYS (loaded from .env)
import os
CEREBRAS_API_KEY = os.environ.get("CEREBRAS_API_KEY", "")
TAVILY_API_KEY   = os.environ.get("TAVILY_API_KEY", "")
SERPER_API_KEY   = os.environ.get("SERPER_API_KEY", "")

# ── SCAN FILTERS ──────────────────────────────────────────
GAP_MIN       = 1.0    # minimum gap % to consider
GAP_MAX       = 8.0    # max gap (above = too extended, skip)
VIX_HIGH      = 20.0   # above this: Tier 1 only, half size
MIN_VOLUME_CR = 5.0    # minimum avg 20-day traded value in crore (LIQUIDITY GATE)

# ── OUTPUT CAPS ───────────────────────────────────────────
MAX_TIER1 = 5
MAX_TIER2 = 8   # reduced from 10, quality over quantity

# ── LLM CALL CAP ─────────────────────────────────────────
MAX_LLM_CALLS = 80   # per run (Groq free tier, 80 is safe)

# ── SCORE THRESHOLDS ─────────────────────────────────────
TIER1_MIN_SCORE = 72   # was 75, slightly relaxed for Groq
TIER2_MIN_SCORE = 48
SKIP_BELOW      = 40

# ── MACRO RSS FEEDS ───────────────────────────────────────
RSS_FEEDS = {
    "ET":    "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    "MINT":  "https://www.livemint.com/rss/markets",
    "MC":    "https://www.moneycontrol.com/rss/marketreports.xml",
}
# Reuters removed — rarely has India-specific stock names, adds noise to velocity scorer

# ── EXACT NSE DESC CLASSIFICATION (from real NSE data) ───────
# These are exact desc field values from NSE feed

NSE_SKIP_EXACT = {
    'Post Buyback Public Announcement',
    'Analysts/Institutional Investor Meet/Con. Call Updates',
    'General Updates',
    'Copy of Newspaper Publication',
    'Trading Window',
    'Certificate under SEBI (Depositories and Participants) Regulations, 2018',
    'Monitoring Agency Report',
    'Price movement',
    'Record Date',
    'Spurt in Volume',
    'Dividend',
    'Statement of deviation(s) or variation(s) under Reg. 32',
    'Committee Meeting Updates',
    'Corrigendum',
    'Amendment to AOA/MOA',
    'Change in Auditors',
    'Resignation of Statutory Auditor',
    'Updates',
}

NSE_TIER1_EXACT = {
    # Moved to Tier2 — 95% are routine shareholding disclosures, not trade signals
    'Open Offer',
    'Public Announcement-Open Offer',
    'Post Buyback Public Announcement',
    'Acquisition',
    'Scheme of Arrangement',
    'Reply to Clarification- Financial results',
    'News Verification',
    'Final  forensic  audit  report',
    'Diversification/Disinvestment',
    'Sale or disposal',
}

NSE_SKIP_EXTRA = {
    'Resignation of Director/KMP/SMP',
    'Resignation',
    'Appointment',
    'Cessation',
    'Change in Director(s)',
    'ESOP/ESOS/ESPS',
    'Options to purchase securities',
    'Allotment of Securities',
    'Bonus',
    'Integrated Filing- Financial',
    'Giving guarantees/indemnity/ becoming a surety for third party',
    'Investor Presentation',
    'Action(s) taken or orders passed',
    'Other Restructuring',
}

NSE_TIER2_EXACT = {
    'Bagging/Receiving of orders/contracts',
    'Awarding of order(s)/contract(s)',
    # Disclosure under SEBI Takeover Regulations -> handled in scorer directly
    'Outcome of Board Meeting',
    'Press Release',
    'Resignation',
    'Resignation of Director/KMP/SMP',
    'Credit Rating',
    'Credit Rating- Revision',
    'Change in Management',
    'Change in Director(s)',
    'Allotment of Securities',
    'Issue of Securities',
    'ESOP/ESOS/ESPS',
    'Options to purchase securities',
    'Investor Presentation',
    'Appointment',
    'Cessation',
    'Action(s) taken or orders passed',
    'Other Restructuring',
    'Integrated Filing- Financial',
    'Giving guarantees/indemnity/ becoming a surety for third party',
    'Disclosure of material issue',
    'Bonus',
}

# ── SKIP FILTERS (garbage announcements) ─────────────────
SKIP_SUBJECTS = [
    "agm", "annual general meeting", "compliance", "regulation 33", "regulation 30",
    "trading window", "loss of share certificate", "change of address", "postal ballot",
    "scrutinizer report", "voting result", "outcome of agm", "proceedings of agm",
    "book closure", "copy of newspaper", "newspaper publication", "monitoring agency report",
    "statement of deviation", "annual report", "analyst meet", "investor meet",
    "price movement", "corrigendum", "erratum",
    "over-subscription", "oversubscription", "offer for sale",
    "intimation of board meeting",
    "change in auditor",
    "appointment of statutory auditor",
    "reappointment",
    "forfeiture of shares",
    "sub-division", "stock split record date",
    "increase in authorised capital",
    "renaming", "name change",
    # Removed: "amendment", "revision to" — these can contain material changes
]

# NSE uses "Updates" as subject for many real catalysts — never skip on subject alone
# These are checked in DETAILS only
SKIP_SUBJECTS_EXACT = {
    "updates",          # too broad — check details instead
    "general updates",
    "outcome of agm",
    "proceedings of agm",
    "book closure notice",
}

SKIP_DETAILS = [
    "recommended a dividend", "declared dividend", "interim dividend",
    "regulation 30 of sebi", "trading window closure", "loss of share",
    "newspaper publication", "change in registered office",
]

# ── TIER 1 KEYWORDS (high conviction) ────────────────────
TIER1_DETAIL_KEYWORDS = [
    "usfda", "fda approval", "anda approved", "ema approval",
    "open offer", "letter of offer", "public announcement", "takeover",
    "change of control", "buyback", "buy back", "buy-back", "repurchase",
    "merger", "amalgamation", "scheme of arrangement",
    "demerger",
    "de-merger",
    "separate listing",
    "spin-off",
    "acquisition of", "acquires", "acquired",
    "large order", "order received", "order win", "bagged", "order book",
    "capacity addition", "new plant", "greenfield", "brownfield",
    "rumour verification", "news verification", "clarification sought",
    "joint venture", "patent grant", "patent approved",
    "termination of agreement",   # can be bullish or bearish — LLM decides
    "strategic investment",
    "qualified institutional placement", "qip",
    "rights issue",                # dilution signal — LLM scores direction
]

TIER2_DETAIL_KEYWORDS = [
    "financial results for the period", "quarterly results", "half yearly results",
    "resignation of", "cessation of", "appointment of", "appoints",
    "allotment of equity", "issue of securities",
    "esop", "employee stock option",
    "agreement signed", "agreements",
    "new subsidiary", "incorporation",
    "investor presentation",
    "credit rating",               # upgrade = bullish, downgrade = bearish
    "debt restructuring",
    "nclt", "insolvency",          # high volatility events
]

TIER1_SUBJECTS = [
    "open offer", "buyback", "buy back", "usfda", "fda approval",
    "merger", "amalgamation", "acquisition", "takeover", "delisting",
    "capacity addition", "qip", "rights issue",
]

TIER2_SUBJECTS = [
    "outcome of board meeting", "general updates", "updates", "agreements",
    "appointment", "change in director", "resignation", "allotment of securities",
    "news verification", "reply to clarification", "rumour verification",
    "issue of securities", "investor presentation", "press release",
    "credit rating", "outcome of nclt",
]

# ── PARENT-SUBSIDIARY MAP (AGM on these = check for delisting/merger)
SUBSIDIARY_MAP = {
    "UNICHEMLAB": "IPCALAB",
    "RECLTD": "PFC",
    "GLENMARK": "GLENMARKLIFE",
    "TATACHEM": "TATACHEMICALS",
    "LTIM": "LT",
}

# ── KNOWN LIQUID F&O UNIVERSE (baseline check) ───────────
# If a scored stock is NOT in this set AND has low volume, flag it
# This is not a hardcoded watchlist — it's a liquidity hint set
FNO_UNIVERSE_HINT = {
    "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS", "WIPRO", "AXISBANK",
    "SBIN", "KOTAKBANK", "TATAMOTORS", "TATASTEEL", "MARUTI", "BAJFINANCE",
    "BAJAJFINSV", "LT", "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB",
    "ADANIPORTS", "ULTRACEMCO", "HINDALCO", "JSWSTEEL", "ONGC", "NTPC",
    "POWERGRID", "COALINDIA", "BPCL", "IOC", "TECHM", "HCLTECH",
    "INDUSINDBK", "FEDERALBNK", "BANDHANBNK", "PNB", "BANKBARODA",
    "ZOMATO", "PAYTM", "NYKAA", "IRCTC", "HAL", "BEL", "BHEL",
    "AUROPHARMA", "GLENMARK", "LUPIN", "MANKIND", "TORNTPHARM",
    "VOLTAS", "HAVELLS", "POLYCAB", "DIXON", "AMBER",
}


def check_keys():
    warnings = []
    if not GROQ_API_KEY:
        warnings.append("GROQ_API_KEY missing")
    if not GEMINI_API_KEY:
        warnings.append("GEMINI_API_KEY missing")
    if not TELEGRAM_TOKEN:
        warnings.append("TELEGRAM_BOT_TOKEN missing")
    if not TELEGRAM_CHAT:
        warnings.append("TELEGRAM_CHAT_ID missing")
    if warnings:
        print(f"[KAAL] ⚠️  KEY WARNING: {', '.join(warnings)}")
        print("[KAAL] Scores will be rule-based only if LLM keys are missing.")
    return warnings
