"""
kaal_config.py
All configuration. No hardcoded watchlist here.
Watchlist is dynamically generated by evening scan → saved to data/watchlist.txt
"""
import os

def load_env():
    for path in [
        os.path.expanduser("~/kaal/kaal_v2/kaal/.env"),
        os.path.expanduser("~/kaal/.env"),
        os.path.join(os.path.dirname(__file__), ".env"),
    ]:
        if os.path.exists(path):
            for line in open(path):
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())
            break

load_env()

# ── TELEGRAM ──────────────────────────────────────────────
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT  = os.environ.get("TELEGRAM_CHAT_ID", "")

# ── GROQ + GEMINI ─────────────────────────────────────────
GROQ_API_KEY   = os.environ.get("GROQ_API_KEY", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

# ── EXTRA LLM KEYS (loaded from .env)
import os
CEREBRAS_API_KEY = os.environ.get("CEREBRAS_API_KEY", "")
TAVILY_API_KEY      = os.environ.get("TAVILY_API_KEY", "")
MARKETAUX_API_KEY  = os.environ.get("MARKETAUX_API_KEY", "")
SERPER_API_KEY   = os.environ.get("SERPER_API_KEY", "")

# ── SCAN FILTERS ──────────────────────────────────────────
GAP_MIN       = 1.0    # minimum gap % to consider
GAP_MAX       = 8.0    # max gap (above = too extended, skip)
VIX_HIGH      = 20.0   # above this: Tier 1 only, half size
MIN_VOLUME_CR = 5.0    # minimum avg 20-day traded value in crore (LIQUIDITY GATE)

# ── OUTPUT CAPS ───────────────────────────────────────────
MAX_TIER1 = 5
MAX_TIER2 = 8   # reduced from 10, quality over quantity

# ── LLM CALL CAP ─────────────────────────────────────────
MAX_LLM_CALLS = 80   # per run (Groq free tier, 80 is safe)

# ── SCORE THRESHOLDS ─────────────────────────────────────
TIER1_MIN_SCORE = 75   # was 75, slightly relaxed for Groq
TIER2_MIN_SCORE = 48
SKIP_BELOW      = 40

# ── MACRO RSS FEEDS ───────────────────────────────────────
RSS_FEEDS = {
    "ET":   "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    "MINT": "https://www.livemint.com/rss/markets",
    "BL":   "https://www.thehindubusinessline.com/markets/stock-markets/?service=rss",
    "GNEWS_MARKET":  "https://news.google.com/rss/search?q=NSE+BSE+stock+India+today&hl=en-IN&gl=IN&ceid=IN:en",
}
# GNEWS_POLICY + GNEWS_GOVT removed — Google News search returns stale archive
# articles (months/years old) for niche policy queries, not fresh news.
# Policy detection now relies on Tavily queries instead.
# PIB removed — JS-rendered, not parseable via RSS or BeautifulSoup
# MC removed June 21 2026 — moneycontrol.com/rss/latestnews.xml confirmed
# serving stale April 2024 broker-call archive despite filename. Both
# marketreports.xml and latestnews.xml tested broken. Revisit if a working
# MC feed URL is found.
# Reuters removed — rarely has India-specific stock names, adds noise to velocity scorer

# ── EXACT NSE DESC CLASSIFICATION (from real NSE data) ───────
# These are exact desc field values from NSE feed

NSE_SKIP_EXACT = {
    'Post Buyback Public Announcement',
    'Analysts/Institutional Investor Meet/Con. Call Updates',
    'General Updates',
    'Copy of Newspaper Publication',
    'Trading Window',
    'Certificate under SEBI (Depositories and Participants) Regulations, 2018',
    'Monitoring Agency Report',
    'Price movement',
    'Record Date',
    'Spurt in Volume',
    'Dividend',
    'Statement of deviation(s) or variation(s) under Reg. 32',
    'Committee Meeting Updates',
    'Corrigendum',
    'Amendment to AOA/MOA',
    'Change in Auditors',
    'Resignation of Statutory Auditor',
    'Updates',
}

NSE_TIER1_EXACT = {
    # Moved to Tier2 — 95% are routine shareholding disclosures, not trade signals
    'Open Offer',
    'Public Announcement-Open Offer',
    'Post Buyback Public Announcement',
    'Acquisition',
    'Scheme of Arrangement',
    'Reply to Clarification- Financial results',
    'News Verification',
    'Final  forensic  audit  report',
    'Diversification/Disinvestment',
    'Sale or disposal',
}

NSE_SKIP_EXTRA = {
    'Resignation of Director/KMP/SMP',
    'Resignation',
    'Appointment',
    'Cessation',
    'Change in Director(s)',
    'ESOP/ESOS/ESPS',
    'Options to purchase securities',
    'Allotment of Securities',
    'Bonus',
    'Integrated Filing- Financial',
    'Giving guarantees/indemnity/ becoming a surety for third party',
    'Investor Presentation',
    'Action(s) taken or orders passed',
    'Other Restructuring',
}

NSE_TIER2_EXACT = {
    'Bagging/Receiving of orders/contracts',
    'Awarding of order(s)/contract(s)',
    # Disclosure under SEBI Takeover Regulations -> handled in scorer directly
    'Outcome of Board Meeting',
    'Press Release',
    'Resignation',
    'Resignation of Director/KMP/SMP',
    'Credit Rating',
    'Credit Rating- Revision',
    'Change in Management',
    'Change in Director(s)',
    'Allotment of Securities',
    'Issue of Securities',
    'ESOP/ESOS/ESPS',
    'Options to purchase securities',
    'Investor Presentation',
    'Appointment',
    'Cessation',
    'Action(s) taken or orders passed',
    'Other Restructuring',
    'Integrated Filing- Financial',
    'Giving guarantees/indemnity/ becoming a surety for third party',
    'Disclosure of material issue',
    'Bonus',
}

# ── SKIP FILTERS (garbage announcements) ─────────────────
SKIP_SUBJECTS = [
    "agm", "annual general meeting", "compliance", "regulation 33", "regulation 30",
    "trading window", "loss of share certificate", "change of address", "postal ballot",
    "scrutinizer report", "voting result", "outcome of agm", "proceedings of agm",
    "book closure", "copy of newspaper", "newspaper publication", "monitoring agency report",
    "statement of deviation", "annual report", "analyst meet", "investor meet",
    "price movement", "corrigendum", "erratum",
    "over-subscription", "oversubscription", "offer for sale",
    "intimation of board meeting",
    "change in auditor",
    "appointment of statutory auditor",
    "reappointment",
    "forfeiture of shares",
    "sub-division", "stock split record date",
    "increase in authorised capital",
    "renaming", "name change",
    # Removed: "amendment", "revision to" — these can contain material changes
]

# NSE uses "Updates" as subject for many real catalysts — never skip on subject alone
# These are checked in DETAILS only
SKIP_SUBJECTS_EXACT = {
    "updates",          # too broad — check details instead
    "general updates",
    "outcome of agm",
    "proceedings of agm",
    "book closure notice",
}

SKIP_DETAILS = [
    "recommended a dividend", "declared dividend", "interim dividend",
    "regulation 30 of sebi", "trading window closure", "loss of share",
    "newspaper publication", "change in registered office",
]

# ── TIER 1 KEYWORDS (high conviction) ────────────────────
TIER1_DETAIL_KEYWORDS = [
    "usfda", "fda approval", "anda approved", "ema approval",
    "open offer", "letter of offer", "public announcement", "takeover",
    "change of control", "buyback", "buy back", "buy-back", "repurchase",
    "merger", "amalgamation", "scheme of arrangement",
    "demerger",
    "de-merger",
    "separate listing",
    "spin-off",
    "acquisition of", "acquires", "acquired",
    "large order", "order received", "order win", "bagged", "order book",
    "capacity addition", "new plant", "greenfield", "brownfield",
    "rumour verification", "news verification", "clarification sought",
    "joint venture", "patent grant", "patent approved",
    "termination of agreement",   # can be bullish or bearish — LLM decides
    "strategic investment",
    "qualified institutional placement", "qip",
    "rights issue",                # dilution signal — LLM scores direction
]

TIER2_DETAIL_KEYWORDS = [
    "financial results for the period", "quarterly results", "half yearly results",
    "resignation of", "cessation of", "appointment of", "appoints",
    "allotment of equity", "issue of securities",
    "esop", "employee stock option",
    "agreement signed", "agreements",
    "new subsidiary", "incorporation",
    "investor presentation",
    "credit rating",               # upgrade = bullish, downgrade = bearish
    "debt restructuring",
    "nclt", "insolvency",          # high volatility events
]

TIER1_SUBJECTS = [
    "open offer", "buyback", "buy back", "usfda", "fda approval",
    "merger", "amalgamation", "acquisition", "takeover", "delisting",
    "capacity addition", "qip", "rights issue",
]

TIER2_SUBJECTS = [
    "outcome of board meeting", "general updates", "updates", "agreements",
    "appointment", "change in director", "resignation", "allotment of securities",
    "news verification", "reply to clarification", "rumour verification",
    "issue of securities", "investor presentation", "press release",
    "credit rating", "outcome of nclt",
]

# ── PARENT-SUBSIDIARY MAP (AGM on these = check for delisting/merger)




# ── BUDGET DAY SECTOR PROXY MAP ──────────────────────────────────────────────
# When budget announces allocation for a sector → these stocks benefit
BUDGET_PROXY_MAP = {
    # Infrastructure
    "RAILWAY BUDGET":       ["RVNL", "IRFC", "IRCON", "RAILTEL", "TITAGARH", "TEXRAIL"],
    "RAILWAY ALLOCATION":   ["RVNL", "IRFC", "IRCON", "RAILTEL", "TITAGARH"],
    "INFRASTRUCTURE PUSH":  ["LT", "NCC", "KNRCON", "PNCINFRA", "HG INFRA", "GPPL"],

    # Defence
    "DEFENCE BUDGET":       ["HAL", "BEL", "PARAS", "MIDHANI", "BHEL", "BEML", "MTAR"],
    "DEFENCE ALLOCATION":   ["HAL", "BEL", "PARAS", "MIDHANI", "BHEL"],
    "DEFENCE INDIGENISATION":["HAL", "BEL", "PARAS", "MIDHANI", "MTAR"],

    # Renewable energy
    "SOLAR BUDGET":         ["WAAREEENER", "TATAPOWER", "ADANIGREEN", "SJVN", "NTPC"],
    "GREEN ENERGY PUSH":    ["WAAREEENER", "TATAPOWER", "ADANIGREEN", "SJVN"],
    "RENEWABLE TARGET":     ["WAAREEENER", "TATAPOWER", "ADANIGREEN", "SJVN", "NTPC"],

    # Housing
    "AFFORDABLE HOUSING BUDGET": ["DLF", "GODREJPROP", "PRESTIGE", "OBEROIRLTY", "PHOENIXLTD"],
    "PMAY ALLOCATION":      ["DLF", "GODREJPROP", "PRESTIGE", "JKCEMENT", "ULTRACEMCO"],
    "HOUSING FOR ALL":      ["DLF", "GODREJPROP", "PRESTIGE", "JKCEMENT"],

    # Agriculture
    "FARM BUDGET":          ["PIIND", "BAYER", "UPL", "DHANUKA", "RALLIS"],
    "KISAN FUND":           ["PIIND", "UPL", "DHANUKA", "RALLIS"],
    "MSP INCREASE":         ["PIIND", "UPL", "DHANUKA"],

    # EV
    "EV BUDGET":            ["TATAMOTORS", "MAHINDRA", "OLECTRA", "TATAPOWER", "HBLPOWER"],
    "EV INCENTIVE":         ["TATAMOTORS", "MAHINDRA", "OLECTRA", "TATAPOWER"],
    "EV SUBSIDY":           ["TATAMOTORS", "MAHINDRA", "OLECTRA"],

    # PSU banks / credit
    "PSU BANK RECAP":       ["SBIN", "PNB", "BANKBARODA", "CANBK", "UNIONBANK"],
    "CREDIT GUARANTEE":     ["SBIN", "PNB", "BANKBARODA", "SIDBI"],

    # Digital India
    "DIGITAL INDIA":        ["CDSL", "CAMS", "LTIM", "INFY", "TCS"],
    "TECH PUSH":            ["CDSL", "LTIM", "INFY", "WIPRO"],

    # Healthcare
    "HEALTH BUDGET":        ["APOLLOHOSP", "MAXHEALTH", "FORTIS", "SUNPHARMA", "CIPLA"],
    "AYUSHMAN BHARAT":      ["APOLLOHOSP", "MAXHEALTH", "FORTIS", "STARHEALTH"],
}

# ── USFDA PROXY MAP ──────────────────────────────────────────────────────────
# When one pharma gets USFDA approval → check if peers make same drug
# When one pharma gets import alert → entire sector gets cautious
USFDA_SYMPATHY_MAP = {
    # Major Indian pharma companies — approval in one benefits peers
    "SUNPHARMA":   ["DRREDDY", "CIPLA", "LUPIN", "AUROPHARMA", "ZYDUSLIFE"],
    "DRREDDY":     ["SUNPHARMA", "CIPLA", "LUPIN", "AUROPHARMA"],
    "CIPLA":       ["SUNPHARMA", "DRREDDY", "LUPIN", "AUROPHARMA"],
    "LUPIN":       ["SUNPHARMA", "DRREDDY", "CIPLA", "AUROPHARMA"],
    "AUROPHARMA":  ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN"],
    "ZYDUSLIFE":   ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN"],
    "GLENMARK":    ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN"],
    "ALKEM":       ["SUNPHARMA", "CIPLA", "LUPIN"],
    "TORNTPHARM":  ["SUNPHARMA", "CIPLA", "LUPIN"],
}

# USFDA keywords
USFDA_APPROVAL_KEYWORDS = [
    "USFDA APPROVAL", "US FDA APPROVAL", "USFDA APPROVED",
    "USFDA HAS APPROVED", "FDA HAS APPROVED",
    "ANDA APPROVAL", "NDA APPROVAL", "ABBREVIATED NEW DRUG APPLICATION",
    "USFDA FINAL APPROVAL", "USFDA TENTATIVE APPROVAL",
    "ESTABLISHMENT INSPECTION REPORT ISSUED",
    "VOLUNTARY ACTION INDICATED",
]

USFDA_WARNING_KEYWORDS = [
    "USFDA IMPORT ALERT", "FDA IMPORT ALERT",
    "WARNING LETTER", "USFDA WARNING",
    "FORM 483", "OFFICIAL ACTION INDICATED", "OAI",
    "COMPLETE RESPONSE LETTER", "CRL",
]

# ── NEGATIVE PROXY MAP ───────────────────────────────────────────────────────
# When trigger found in news → these stocks get BEARISH flag + score penalized
NEGATIVE_PROXY_MAP = {
    # Global IT bellwether misses → Indian IT falls
    "ACCENTURE MISS":       ["WIPRO", "INFY", "TCS", "HCLTECH", "TECHM", "LTIM", "MPHASIS"],
    "ACCENTURE RESULTS":    ["WIPRO", "INFY", "TCS", "HCLTECH", "TECHM"],
    "IBM MISS":             ["WIPRO", "INFY", "TCS", "HCLTECH"],
    "COGNIZANT MISS":       ["WIPRO", "INFY", "TCS", "HCLTECH", "TECHM"],
    "NASDAQ CRASH":         ["WIPRO", "INFY", "TCS", "HCLTECH", "TECHM", "LTIM"],

    # US pharma/FDA negative → Indian pharma falls
    "FDA WARNING LETTER":   ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN", "AUROPHARMA"],
    "FDA IMPORT ALERT":     ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN", "AUROPHARMA"],

    # China slowdown → metal stocks fall
    "CHINA SLOWDOWN":       ["TATASTEEL", "HINDALCO", "JSWSTEEL", "SAIL", "NALCO"],
    "CHINA DEMAND FALL":    ["TATASTEEL", "HINDALCO", "JSWSTEEL"],

    # Crude spike → aviation, paint, tyre fall
    "CRUDE SPIKE":          ["INDIGO", "SPICEJET", "ASIANPAINT", "BERGER", "MRF", "APOLLOTYRE"],
    "OIL PRICE RISE":       ["INDIGO", "SPICEJET", "ASIANPAINT", "BERGER"],

    # US recession fears → export-heavy IT/pharma fall
    "US RECESSION":         ["WIPRO", "INFY", "TCS", "SUNPHARMA", "DRREDDY"],
    "FED RATE HIKE":        ["BANKBARODA", "PNB", "SBIN", "HDFC", "ICICIBANK"],
}

# ── PROXY/INDIRECT BENEFICIARY MAP ───────────────────────────────────────────
# When trigger keyword found in news → flag these listed stocks as Tier1
# Format: "news keyword": ["SYMBOL1", "SYMBOL2", ...]

PROXY_MAP = {
    # NSE IPO — companies selling NSE shares via OFS
    # Each milestone is a separate trigger with its own cooldown
    "NSE IPO DRHP FILED":     ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],
    "NSE SEBI OBSERVATION":   ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],
    "NSE IPO PRICE BAND":     ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],
    "NSE IPO LISTING":        ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX", "CDSL"],
    "NSE IPO":                ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],
    "NSE DRHP":               ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],
    "NSE LISTING":            ["NIACL", "IFCI", "GICRE", "BSELTD", "MCX"],

    # Capital market theme — when NSE IPO files, these also benefit
    "NSE IPO FILING": ["CDSL", "CAMS", "KFINTECH", "BSE"],

    # Adani group — any Adani entity news benefits peers
    "ADANI ACQUISITION": ["ADANIPORTS", "ADANIENT", "ADANIGREEN", "ADANIPOWER"],
    "ADANI ORDER": ["ADANIPORTS", "ADANIENT", "ADANIGREEN"],

    # Defence sector — any large defence order benefits peers
    "DEFENCE ORDER": ["HAL", "BEL", "PARAS", "MIDHANI", "BHEL", "BEML"],
    "DEFENCE CONTRACT": ["HAL", "BEL", "PARAS", "MIDHANI", "BHEL"],
    "MILITARY ORDER": ["HAL", "BEL", "PARAS", "MTAR"],

    # PSU bank recapitalisation
    "PSU BANK RECAPITAL": ["SBIN", "PNB", "BANKBARODA", "CANBK", "UNIONBANK"],

    # Insurance sector — any insurance regulation benefits all
    "INSURANCE FDI": ["LICI", "GICRE", "NIACL", "STARHEALTH"],
    "INSURANCE REGULATION": ["LICI", "GICRE", "NIACL"],

    # Real estate — RERA or govt housing scheme benefits all
    "AFFORDABLE HOUSING": ["DLF", "GODREJPROP", "PRESTIGE", "OBEROIRLTY"],
    "RERA AMENDMENT": ["DLF", "GODREJPROP", "PRESTIGE"],

    # Pharma — USFDA clearance for one benefits sector
    "USFDA APPROVAL": ["SUNPHARMA", "DRREDDY", "CIPLA", "LUPIN", "AUROPHARMA"],

    # EV sector — national policy only, state-level excluded
    "NATIONAL EV POLICY": ["TATAMOTORS", "MAHINDRA", "OLECTRA", "TATAPOWER"],
    "PLI EV SCHEME": ["TATAMOTORS", "MAHINDRA", "OLECTRA"],
}

# News keywords that trigger proxy scan
PROXY_TRIGGER_KEYWORDS = list(PROXY_MAP.keys())

# Open offers with known close dates — skip after close date
CLOSED_OPEN_OFFERS = {
    "RBLBANK": "2026-06-12",  # Emirates NBD offer closed June 12
}

SUBSIDIARY_MAP = {
    "UNICHEMLAB": "IPCALAB",
    "RECLTD": "PFC",
    "GLENMARK": "GLENMARKLIFE",
    "TATACHEM": "TATACHEMICALS",
    "LTIM": "LT",
}

# ── KNOWN LIQUID F&O UNIVERSE (baseline check) ───────────
# If a scored stock is NOT in this set AND has low volume, flag it
# This is not a hardcoded watchlist — it's a liquidity hint set
FNO_UNIVERSE_HINT = {
    "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS", "WIPRO", "AXISBANK",
    "SBIN", "KOTAKBANK", "TATAMOTORS", "TATASTEEL", "MARUTI", "BAJFINANCE",
    "BAJAJFINSV", "LT", "SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB",
    "ADANIPORTS", "ULTRACEMCO", "HINDALCO", "JSWSTEEL", "ONGC", "NTPC",
    "POWERGRID", "COALINDIA", "BPCL", "IOC", "TECHM", "HCLTECH",
    "INDUSINDBK", "FEDERALBNK", "BANDHANBNK", "PNB", "BANKBARODA",
    "ZOMATO", "PAYTM", "NYKAA", "IRCTC", "HAL", "BEL", "BHEL",
    "AUROPHARMA", "GLENMARK", "LUPIN", "MANKIND", "TORNTPHARM",
    "VOLTAS", "HAVELLS", "POLYCAB", "DIXON", "AMBER",
}


def check_keys():
    warnings = []
    if not GROQ_API_KEY:
        warnings.append("GROQ_API_KEY missing")
    if not GEMINI_API_KEY:
        warnings.append("GEMINI_API_KEY missing")
    if not TELEGRAM_TOKEN:
        warnings.append("TELEGRAM_BOT_TOKEN missing")
    if not TELEGRAM_CHAT:
        warnings.append("TELEGRAM_CHAT_ID missing")
    if warnings:
        print(f"[KAAL] ⚠️  KEY WARNING: {', '.join(warnings)}")
        print("[KAAL] Scores will be rule-based only if LLM keys are missing.")
    return warnings
